### ISSUE TITLE
Add project selection step to Duplicate workspace action

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/mise#135]
Currently when you use the Duplicate workspace action the new workspace is created in the same project as the source workspace. Sometimes this will be what the user wants, but other times they might want it to go into another project. In particular I'm concerned about the case where the user visits the Explore section, sees a workspace they like and duplicates it (which is arguably a primary purpose of the Explore section). In that scenario, it is extremely likely that the current project is **not** the appropriate place for the duplicated workspace. In fact, we probably shouldn't allow a duplicated workspace to go into the source project when the action is done through Explore (if the user has Edit rights to the source project, they should probably just duplicate the workspace within their project section of Mise, rather than the more community-oriented Explore section).

But if a duplicated workspace must or can be duplicated into a different project than the source project, we need to enable the user to indicate which project it should go into (unless we use the "default project" idea we discussed early on, but I prefer the explicit project selection approach, which we might be able to reuse for the "Move workspace" action as well).

Here's a suggestion to consider.

<img width="1197" alt="Screen Shot 2021-05-14 at 3 10 10 PM" src="https://user-images.githubusercontent.com/101482/118338141-3fb2ad80-b4ca-11eb-9d39-cb896c2b44d7.png">

---
- **A:** When the user selects the "Duplicate workspace" action, whether from the sidebar button or a workspace card option menu item (the screenshot shows both for illustration purposes but in reality you don't see both of these options in the same context), we display a modal for the user to make a destination project selection.
- **B:** General modal should be visually similar to the Manage collaboration modal for consistency, but titled `Duplicate workspace`
- **C:** Modal text `Where do you want the duplicated workspace to be created?`
- **D:** Dropdown menu label `Select a project`
- **E:** Dropdown menu. The options should list all the projects the user has Editor or higher privileges to. I guess order is alphabetically? Ideally, I'd say the default choice is the current project, but if they are duplicating from Explore they likely won't have Edit privileges to the source project so that feels more complicated than a strict alphabetical list of eligible projects.
- **F:** Cancel and Duplicate buttons. We don't show a Cancel button on the Manage collaboration modal, but it feels more useful here because it is more clear to the user who decides against duplicating how to get out of it (rather than depending on their knowledge of canceling modals in the other common ways). I don't feel too strongly but in general I like an explicit Cancel button on all modals unless it really feels unnecessary for some reason.

As I alluded to above, I think we could use an almost identical pattern to enable the "Move workspace..." action, but I'll wait and see if there are concerns about this suggestion before worrying about that.

**Comment by cbeer** [comment]
I think this is roughly what the Move workspace... does, but bootstrap 5.0.0 broke their modals so we're waiting on the 5.0.1 release 🤷‍♂️

**Comment by ggeisler** [comment]
Oh. I didn't realize the Move workspace action was/had been working. I just thought you hadn't gotten to it yet.

But that's good then, maybe we can just repurpose that for Duplicate, when it is working again.
