### ISSUE TITLE
Scope "Favorite" workspaces by user

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/mise#141]
Not sure if I'm misunderstanding something but when I log in on -stage and look at my Dashboard page I see a favorited workspace that I didn't favorite:

<img width="1215" alt="Screen Shot 2021-05-19 at 5 16 12 PM" src="https://user-images.githubusercontent.com/101482/118900707-74f23d80-b8c6-11eb-9ec4-fc5f791caaaa.png">

I have access to the project and workspace, but the project doesn't show any collaborators, so I think this might be due to being a site admin?

I guess this ticket is just to say, I don't think the current user should see a workspace in "Favorite workspaces" that was favorited by another user, even if the current user has access to that workspace. The favorite property should be a user-workspace relationship. This ideally should apply to admin users as well, if that's possible.

**Comment by camillevilla** [comment]
@ggeisler I checked on this in stage with my non-Stanford account and only site admins can see ALL favorite workspaces. I'll work on fixing that up for admins but it doesn't sound like our tests users will see this.

**Comment by ggeisler** [comment]
Cool, thanks @camillevilla!

**Comment by ggeisler** [comment]
To add a bit to this, I think the underlying issue I'm trying to raise here is that it appears to me (first from the UI issue that prompted me to create this ticket but also now that I've looked at the database structure) that the favorite attribute is an attribute of `Workspace`, not `User`. So a given workspace is either favorited or not, regardless of which user is viewing it. This means that if Camille favorites a workspace that I also have access to (as a regular Mise user, not an admin), it is shown as a favorited workspace to me, even if I don't care much about it.

I believe that what we want is for the favorite attribute to be an attribute of a user-workspace combination. I think this might mean (in strictly database terms, not trying to suggest how anything is actually implemented in the app) a new `user_workspace` table where there's a composite primary key consisting of `user_id` + `workspace_id` and a boolean `favorited` attribute that is true when that user favorites that workspace. That would then enable us to show a given workspace as favorited for a specific user only if they were the one to favorite that workspace.

It's possible I'm misunderstanding something about the technical design here, but from a UX and database theory perspective, this is what makes sense to me.

**Comment by cbeer** [comment]
Favorites were implemented before we had any notion of collaborators, so the initial pass was functional the same either way.. and I guess I assumed favorites were "welcome to our project, here's some of our workspaces we've highlighted for you" and not favorites-as-bookmarks 🤷‍♂️ .

**Comment by ggeisler** [comment]
Sure, I understand why things are the way they are, but yes, I think it would be useful to move to favorites-as-bookmarks. Thanks for changing the ticket title to reflect that goal.
