### ISSUE TITLE
Auto-save workspaces or enhance the Save workspace button

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/mise#144]
This is more of a question/design needed issue at this stage. I'm not certain which of the alternative user stories below best represent our real potential users. 

**User story A**: As Mise user, when working on resources in my workspace, the current state of my workspace should be saved automatically so I don't have to know to and remember to save the workspace or risk losing changes I've made when leaving the workspace.

**User story B**: As Mise user, when working on resources in my workspace, I should have a clear and noticeable indication when the current state of my workspace has unsaved changes so I know that I either need to save the workspace or intentionally lose recent changes I've made when leaving the workspace.

**Comment by cbeer** [comment]
I think we'll want to do B, and have the browser prompt if you try to leave the page and have unsaved changes. Doing A seems like it might be tricky to figure out the right granularity of when to save.

**Comment by ggeisler** [comment]
Sure, B seems much simpler. Perhaps we could just go with the standard browser prompt dialog with the text `You have unsaved changes to your workspace. Are you sure you want to leave this page?`, along with the standard Cancel and OK buttons.

It's pretty generic but should be relatively easy to implement and would ensure Mise users aren't accidentally losing workspace work due to forgetting they need to save the workspace.

**Comment by mjgiarlo** [comment]
@ggeisler happy to give you a tour/demo of this next week. It was a bit too involved to do justice in a PR screencast.

**Comment by ggeisler** [comment]
@mjgiarlo No need, I don't think, it looks fine to me. Ideally we'd obviously rather present the user with a more Mise-specific message (which I see is in the code) but I guess we're at the mercy of the browsers for this.
